### ISSUE TITLE
Defensive xpath patching

### ISSUE THREAD

**Issue by Mehni** [LocoNeko/RoadsOfTheRim#1]
https://github.com/LocoNeko/RoadsOfTheRim/blob/84dcd86803611aafb98eb8450990fc6c7f05f7b7/Patches/patches.xml#L38

Your xpath currently does not take into account other mods adding Comps to the caravan, resulting in duplicate xml nodes and effectively a failed patch. I recommend a patch like this: https://github.com/Mehni/MoreFactionInteraction/blob/master/Patches/MoreFactionInteraction.xml#L40-L62

Doing it that way prevents issues and increases compatibility with other mods.

**Comment by LocoNeko** [comment]
Thanks Mehni, much appreciated ! I'll do that ASAP. Very nice of you to
point to some code as well.

Cheers,
Guillaume (LocoNeko)

**Comment by LocoNeko** [comment]
*actually* fixed (see issue #3 )
