### ISSUE TITLE
In Situ resource gathering

### ISSUE THREAD

**Issue by LocoNeko** [LocoNeko/RoadsOfTheRim#21]
Add devices ("construction kits", "road builders" or "Road Resource Collectors") that can help reduce the amount of resources needed by a construction site, at the cost of more work.

Those devices reduce the total amount of work needed, so the net effect could be a reduced construction time.

Each pawn can control one device

Those devices need to be researched, they cost steel, components, and maybe advanced components to build.

There are 2 types : one that is able to help with wood & stone, and another that can help with all resources (included steel & chemfuel)

The amount of cost reduction depends on the tile as well. The Sea Ice biome prevents those devices from working.

**Comment by LocoNeko** [comment]
Name : In Situ Road Resource Gatherer (ISR2G)

**Comment by Mihokyo** [comment]
Collect rock and made it block since they build .. with stonecutter's table in caravan inventory ( i've do with 5 people 3600 stones in 5 day(near 144stone block/day for 1 guys) (with construct building, harvest food, i got doggo for collect chunk)
Collect steal.. with miner

**Comment by LocoNeko** [comment]
Done as part of version 2 : 6c04815
