### ISSUE TITLE
Auto-start work when building a site

### ISSUE THREAD

**Issue by LocoNeko** [LocoNeko/RoadsOfTheRim#39]

**Comment by LocoNeko** [comment]
Colsed by 7508788e400dbdb90c85cc18a01b6b64d77a837f

**Comment by zozilin** [comment]
I am sorry to be that guy - can you make auto work an option? The thing is - sometimes I need to cancel a road to plan anew, but it doesn't let me as autowork immediately puts 1 tick of work into construction even with no resources. So, the only way right now is to time when they finish one tile and cancel before they move to the next.
To sum up, one of the options would be great:
1. Auto work as a toggleable option.
2. Construction cancellation when it already started (maybe with confirmation message?)
3. Pawns don't put 1 tick of work into construction when there's nothing to build with.
I don't know anything about programming, so no clue how hard it is. Thank you for the mod.
