### ISSUE TITLE
Glitterworld road dosen't let you go over Impassable tiles

### ISSUE THREAD

**Issue by Zemogiter** [LocoNeko/RoadsOfTheRim#43]
Despite being able to build them over impassable terrain (mountains, haven't tested on ocean) I can't go through them. The caravan just goes around it. Based on #28 that shouldn't be the case. No error in the log is generated.

Save:
https://www.mediafire.com/file/acq6700tslh4zmf/Wasbutunt_Confederation.rws/file

**Comment by LocoNeko** [comment]
Was corrected a long time ago. Re-open and send game file if that happens again
