### ISSUE TITLE
Tribesmen do construct alone, but don't with pack animals

### ISSUE THREAD

**Issue by gorniyy** [LocoNeko/RoadsOfTheRim#44]
When I send one tribesman he constructs the road, but when I send him with some alpacas he just waiting during the day. I thought that problem was that animals were unhealthy, but now they are alright, but man is just resting all the time, he doesn't construct.
(I use the latest version)

**Comment by gorniyy** [comment]
Sorry, tribesmen are working, but there is written that they are waiting. Everything's fine.

**Comment by LocoNeko** [comment]
Closing as per comment above
