### ISSUE TITLE
Can we get an updated README to explain how the AISR2G works?

### ISSUE THREAD

**Issue by sraldleif** [LocoNeko/RoadsOfTheRim#49]
I have no idea how to use it. I have it installed at my base, but my caravan's keep saying they don't have the resources to construct anything?

**Comment by sraldleif** [comment]
Figured out you need to keep it uninstalled and take it with you

**Comment by LocoNeko** [comment]
Cheers ! The Steam community page has a lot of details (https://steamcommunity.com/sharedfiles/filedetails/?id=1613783924), but it's true but it's not exactly clear that the ISR2G must be built, uninstalled, and put in a caravan
