### ISSUE TITLE
Construction getting stuck at 99.9%

### ISSUE THREAD

**Issue by sraldleif** [LocoNeko/RoadsOfTheRim#50]
My caravan will get to 99.9% completion with 1 unit of work left to do, then will just sit there doing nothing.

**Comment by LocoNeko** [comment]
Thanks for the bug report. Can I get your game file ?

**Comment by sraldleif** [comment]
Sure :)
I had to upload it as a txt file since github won't accept rws files.
There should be two roads sitting there at 99.9% completion that I can't manage to finish off.
Do you want my mod list as well, or is that included in the file?

[debug.txt](https://github.com/LocoNeko/RoadsOfTheRim/files/4527953/debug.txt)

**Comment by LocoNeko** [comment]
Thanks. There are heaps of mods in there that I don't have, so I'll try to narrow it down to those that could have an effect and download them, but that will be a painfully slow process. I also notice that you run royalty, which I don't have. Bear with me for a while, I'll try my best.

**Comment by sraldleif** [comment]
Thanks mate! No rush, I just thought I'd let you guys know :)

**Comment by LocoNeko** [comment]
Hi there ! This should be all good now (commit b7f7c3d). Have a look at the discussion on https://steamcommunity.com/sharedfiles/filedetails/?id=1613783924 to see what the bugfix entails. Basically, work will be a little bit slower when you send very few pawns / low construction skill pawns.
Thanks a bunch for taking the time to report this, mate !
