### ISSUE TITLE
Building better roads on top of other roads can instantly drain all road resources and does not construct

### ISSUE THREAD

**Issue by honeymonster93** [LocoNeko/RoadsOfTheRim#60]
Hi LocoNeko, thank you for the great mod!

I posted on the steam page and you said posting here was best so here I am. Here's what I put:

I have been experiencing a bug. I have tried three times now to build an asphalt road where a stone road already exists. When my colonist start work it immediately gives the out of resources message and deletes every single piece of road material my caravan had. On the construction spot it says "Stone left of 444", aka no number at the front saying how much should be left to make to road. So some kind of bug with it calculating the amount of resource needed to make the road? I have the base multiplier set to minimum. Let me know if you would like anymore details. Thanks for the great mod, really enjoy it. :)

In attached save, tile 30.51N 10.95W south down the stone road would lead to this bug.

[Onasan.zip](https://github.com/LocoNeko/RoadsOfTheRim/files/4584984/Onasan.zip)

**Comment by honeymonster93** [comment]
So this isn't just limited to stone -> Asphalt roads. I just had 3k of wood disappear when trying to build a dirt road on top of a dirt path. Had no issue building on previous hex's that had no road already on there.

**Comment by honeymonster93** [comment]
Pics of issue, first of the whole screen, second is zoomed into the important part, the construction site information.

![roadsbug](https://user-images.githubusercontent.com/64886516/81165729-64f10f80-8f8a-11ea-8e2d-8346ea24ea08.png)
![roadsbugsmall](https://user-images.githubusercontent.com/64886516/81165774-789c7600-8f8a-11ea-9fac-3fba2836da6b.png)

**Comment by honeymonster93** [comment]
Here's the save with above issue still intact, the original save I uploaded I had cancelled the construction site that was bugged.

[Onasan (2).zip](https://github.com/LocoNeko/RoadsOfTheRim/files/4586122/Onasan.2.zip)

**Comment by LocoNeko** [comment]
Thanks for the bug report, much appreciated.
You seem not to be working with ISR2G, on which I was mostly focused recently. It seems the rebate for existing roads is not taking the cost modifier from the mod setting correctly, resulting in a 0 cost. I have updated the mod to prevent that.
For your existing game, I suggest copying the save file, and using a text editor search for "RoadConstructionSite", the sites that bugged out have a section of "RotR_site_left" where the first value looks like "\<li\>1.191983E-05\</li\>" change that to "\<li\>1\</li\>" and you should need just one tick to finish the work.
This is reasonably safe but you should work on a copy of your game file first.
Thanks again for helping improve the mod !
Closed by 8d95a5f4a118bd260f272f4de2331479d360d219
