### ISSUE TITLE
Research description for Glitter road building is wrong

### ISSUE THREAD

**Issue by fr0** [LocoNeko/RoadsOfTheRim#61]
It says "Allows construction of Asphalt roads on the world map", which is the exact same as the research description for Asphalt road building.

Probably a copy/paste error.

**Comment by fr0** [comment]
![20200526001935_1](https://user-images.githubusercontent.com/435418/82860176-cb60b200-9ee6-11ea-8b97-e582a8837ee3.jpg)

**Comment by LocoNeko** [comment]
Yes, stupid copy/paste that was corrected in a version that I deleted, and forgot to put back in the master branch... Will fix asap. Thanks a bunch for finding this.

**Comment by LocoNeko** [comment]
Fixed by 57fae4d032948636718492fd85a033bab6b88066
