### ISSUE TITLE
Panel for caravan includes "Waiting" and "Resting" while building road

### ISSUE THREAD

**Issue by fr0** [LocoNeko/RoadsOfTheRim#62]
![20200526001700_1](https://user-images.githubusercontent.com/435418/82860065-85a3e980-9ee6-11ea-89f3-d2b907d3f9da.jpg)

**Comment by LocoNeko** [comment]
Thanks for this. I know of this problem, but it's trickier to fix than it looks. Will try a hotfix ;-)

**Comment by LocoNeko** [comment]
Should have been resolved by e0528f875c2684e5fcce328bc9760c09c7a2687b
