### ISSUE TITLE
{0} unable to build road right now

### ISSUE THREAD

**Issue by greenhaileylj** [LocoNeko/RoadsOfTheRim#72]
I have enough colonists and animals to carry the ISR2G, but I get the above message when I send out a caravan. Only once did I see the option to build a road while out trading and I have no idea why I can't build one now that I'm prepared. What do I do?

**Comment by LocoNeko** [comment]
Sorry mate, I don't maintain this mod any more. You might get lucky asking on Steam to some of the people who made it functional with the latest Rimworld updates. Best of luck !
